repos:
  - repo: local
    hooks:
      - id: nbdev_clean
        name: nbdev_clean
        entry: nbdev_clean
        language: python
        pass_filenames: false
        additional_dependencies:
          - nbdev
  - repo: local
    hooks:
      - id: nbstripout
        name: nbstripout
        entry: nbstripout
        language: python
        pass_filenames: true
        types: [jupyter]
  - repo: local
    hooks:
      - id: nbdev_export
        name: nbdev_export
        entry: bash -c 'if [ ! -z "$(nbdev_export)" ]; then nbdev_export; fi'
        language: python
        pass_filenames: false
        additional_dependencies:
          - nbdev
