name: x
channels:
  - conda-forge
  - fastai
dependencies:
  - python=3.9
  - pip
  - fastcore
  - ipykernel
  - jax
  - jaxlib
  - matplotlib=2
  - nbdev
  - nbstripout
  - numpy
  - openssl
  - papermill
  - pre-commit
  - rsync
  - scikit-image
  - pip:
    - ceviche
